### ISSUE TITLE
Window very wide and not resizable with large boot entries

### ISSUE THREAD

**Issue by V10lator** [Elinvention/efiboots#23]
![image](https://user-images.githubusercontent.com/1312422/141803395-b9668a70-e483-45bb-b486-d0bc8b76fd56.png)
This is way larger than my screen, so it would be nice if the bootentry list could be scrollable.

**Comment by Elinvention** [comment]
Yes, I know about this, but I still have to find a good solution. One thing could be ditching the Gtk.TreeView in favor of a Gtk.ListView, but that would require a lot of work.
Probably there are some features of Gtk.TreeView that I'm missing.
