### ISSUE TITLE
AUR package does not include gtk dependency

### ISSUE THREAD

**Issue by Kytech** [Elinvention/efiboots#28]
The gtk3/gtk4 package is not listed as a dependency in the AUR PKGBUIlD. Came across this when installing/updating efiboots in a QT-based desktop environment such as KDE on Arch on a few different occasions, so GTK had not been installed on my system. (This was also the first application on my system to use gtk4 even though I had gtk3 installed by this point.)

I noticed that you also appear to maintain the AUR package for this application, so I figured that this is one place where I could point this out.

**Comment by Elinvention** [comment]
Yes, I'm the maintainer, but I stopped using arch linux, so I often forget to update the package and test it. Now I should have added the missing gtk4 dependency.
