### ISSUE TITLE
Arch Linux autofs of EFI breaks discovery

### ISSUE THREAD

**Issue by xannor** [Elinvention/efiboots#29]
I was attempting to add a boot parameter to my kernel and I could not run the gui. It would fail with

```
DEBUG:root:Running: findmnt --noheadings --output SOURCE,FSTYPE --mountpoint /efi
Traceback (most recent call last):
  File "/usr/bin/efiboots", line 18, in <module>
    efiboots.run(parsed_args.disk, parsed_args.part)
  File "/usr/lib/python3.9/site-packages/efiboots.py", line 571, in run
    disk, part = auto_detect_esp()
  File "/usr/lib/python3.9/site-packages/efiboots.py", line 125, in auto_detect_esp
    result = find_esp_method()
  File "/usr/lib/python3.9/site-packages/efiboots.py", line 82, in auto_detect_esp_with_findmnt
    source, fstype = subprocess.run(cmd, check=True, capture_output=True, text=True).stdout.strip().split()
```
So I added an additional debug and I found it the problem is that since I have my EFI partition set to automount in my fstab, findmnt sees two mount points and crashes the app.
If I add [-2:] to the end of the line it would only grab the last entry, which fixed my setup, but I do not know if the autofs entry is always first or not.

FYI: the output of the findmnt command on my system:
```
findmnt --noheadings --output SOURCE,FSTYPE --mountpoint /efi
systemd-1      autofs
/dev/nvme0n1p1 vfat
```

**Comment by Elinvention** [comment]
Thanks for reporting this issue. I will try to support this case too. In the mean time, I think you can bypass this issue if you manually pass `--disk /dev/nvme0n1 --part 1` to efiboots.
