### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by bassemolufda** [Elinvention/efiboots#37]
benutzername@Thinkpad-E15:~/Downloads$ git clone https://github.com/Elinvention/efiboots.git
Klone nach 'efiboots'...
remote: Enumerating objects: 260, done.
remote: Counting objects: 100% (135/135), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 260 (delta 78), reused 88 (delta 47), pack-reused 125
Empfange Objekte: 100% (260/260), 111.96 KiB | 3.11 MiB/s, fertig.
Löse Unterschiede auf: 100% (144/144), fertig.

benutzername@Thinkpad-E15:~/Downloads$ cd efiboots/

benutzername@Thinkpad-E15:~/Downloads/efiboots$ python3 efiboots 
Traceback (most recent call last):
  File "/home/benutzername/Downloads/efiboots/efiboots", line 6, in <module>
    import efiboots
  File "/home/benutzername/Downloads/efiboots/efiboots.py", line 9, in <module>
    gi.require_version('Gtk', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0

benutzername@Thinkpad-E15:~/Downloads/efiboots$ sudo uname -a

Linux Thinkpad-E15 5.19.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) x86_64 GNU/Linux

I did not know what the error is. :-(

**Comment by bassemolufda** [comment]
The Solution is install gir1.2-gtk-4.0 in Debian 12 Bookworm.

**Comment by Elinvention** [comment]
I added that package to README.md. Thanks for contributing.
