### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by ViBE-HU** [Elinvention/efiboots#42]
Since there is no package I just copied the old sources to machine by machine. Now I downloaded the newer sources on a newer machine and realised that it is broken. Then I checked the readme again and noticed that the minimum requirement now is Ubuntu 22.10.

I have a few machines with 20.04 and 22.04 but as most long term Ubuntu users I don't have any with 22.10 for tons good reasons. Nobody use non-LTS systems. Makes no sense. So is it possible to add compatibility or are there any workaround for 20.04/22.04 systems to make it run?

**Comment by Elinvention** [comment]
> Nobody use non-LTS systems. Makes no sense.

I guess it does make sense if you want to run any software from a development branch. Someone has to make the software used by the next LTS. By using an LTS distro you have to accept using older software.

Please see https://github.com/Elinvention/efiboots/issues/41#issuecomment-1621937031 for workarounds.
